- import_role:
    name: base_role
  vars:
    systemd_units_system:
      - autorandr.service

- name: Make hooks scripts executable
  file:
    dest: "{{ xdg_config_home }}/autorandr/postswitch"
    mode: 755
