exclude: "^roles/*/files/*|^old_to_migrate/*"
fail_fast: true
default_language_version:
  node: "14.14.0" # Fix Prettier installation issues (see #9459)

repos:
  - repo: http://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/prettier/prettier
    rev: 2.1.2
    hooks:
      - id: prettier

  - repo: https://github.com/ansible/ansible-lint
    rev: v4.2.0
    hooks:
      - id: ansible-lint

  - repo: local
    hooks:
      - id: vagrant
        name: vagrant
        entry: vagrant validate --ignore-provider
        language: system
        files: ^Vagrantfile$

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.16
    hooks:
      - id: circleci-config-validate

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
