- include_role:
    name: _install_packages

- include_role:
    name: _create_directories
    apply:
      become: yes

# TODO: Solve issue of linking
- name: Copy rule files
  copy:
    src: "{{ item }}"
    dest: "{{ rules_directory }}"
  with_fileglob:
    - "{{ role_path }}/files/*.rules"
  become: yes

- name: Copy media configuration file
  copy:
    src: "{{ role_path }}/files/media.conf"
    dest: "{{ media_directory }}"
  become: yes

- include_role:
    name: _enable_start_services

- name: Enable and start SystemD service
  systemd:
    name: udisks2.service
    enabled: yes
    state: started
  become: yes
