- name: Install base package
  aur: name=udisks2
  become: yes

- name: Install optional dependency packages
  aur:
    name:
      - ntfs-3g # Support NTFS
  become: yes

- name: Create rule and media directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ rules_directory }}"
    - "{{ media_directory }}"
  become: yes

# Linked files seem to cause issues
- name: Copy rule files
  copy:
    src: "{{ item }}"
    dest: "{{ rules_directory }}"
  with_fileglob:
    - "{{ role_path }}/files/*.rules"
  become: yes

- name: Copy media configuration file
  copy:
    src: "{{ role_path }}/files/media.conf"
    dest: "{{ media_directory }}"
  become: yes

- name: Enable and start SystemD service
  systemd:
    name: udisks2.service
    enabled: yes
    state: started
  become: yes
