- import_role:
    name: base_role
  vars:
    base_package: udisks2
    additional_packages:
      - ntfs-3g # Support NTFS
    directory_paths:
      - /etc/udev/rules.d
      - /etc/tmpfiles.d
    systemd_units: udisks2.service

- name: Find rule files
  find:
    paths: "{{ role_path }}/files"
    patterns: "*.rules"
  register: rule_files

- name: Link rule files
  file:
    src: "{{ item }}"
    dest: "/etc/udev/rules.d/{{ item | basename }}"
    state: link
    mode: 0644
    force: yes
  become: yes
  with_items:
    - "{{ rule_files.files | map(attribute='path') | list }}"

- name: Link media configuration file
  file:
    src: "{{ role_path }}/files/media.conf"
    dest: /etc/tmpfiles.d/media.conf
    state: link
    mode: 0644
    force: yes
  become: yes
