version: 2.1

executors:
  arch_linux:
    docker:
      - image: weilbith/warhorse-circleci:latest # TODO: Use a fixed version
    working_directory: ~/repository

commands:
  synchronize_packages:
    steps:
      - run: sudo pacman -Sy

jobs:
  lint:
    executor: arch_linux
    steps:
      - checkout
      - synchronize_packages
      - run:
          name: Install testing setup
          command: make install-testing
      - run:
          name: Run tests for linting
          command: make test-lint

  provide:
    executor: arch_linux
    steps:
      - checkout
      - synchronize_packages
      - run:
          name: Install provision setup
          command: make install-provision
      - run:
          name: Run provision
          command: make provide

workflows:
  version: 2
  default:
    jobs:
      - lint
      - provide
