- import_role:
    name: base_role
  vars:
    additional_packages:
      - pcsclite # Smartcard middleware library
      - ccid # Smartcard interface driver
    link_configuration_children: true
    systemd_units_user:
      - gpg-agent.service
      - gpg-agent-ssh.socket
    systemd_units_system:
      - pcscd.service


- name: Note to remember the hardware key import
  debug:
    msg:
      - ""
      - ""
      - "+-------------------------------------------------------------------------------------+"
      - "|                                                                                     |"
      - "|                                   REMEMBER                                          |"
      - "|                                                                                     |"
      - "|  Do not forget to import the public keys from the hardware key. Therefore plug in   |"
      - "|  the key and type the command `gpg --card-edit`. Inside the REPL execute `fetch`.   |"
      - "|                                                                                     |"
      - "+-------------------------------------------------------------------------------------+"
      - ""
      - ""
