# It is essential to set all variables used within the base role.
# Because not all roles including the base role will define each of these
# variables. Thereby they will inherit the undefined variables from their
# predecessor role in the playbook (bug?).
# The default values should either lead to a skipped task or point to the
# default location to verify the existence of a role its files.

# Use true/false for custom boolean variables to simply functional code.
# Use yes/no where injecting into existing Ansible functionality (since we
# simply must)

origin_role_name: "{{ ansible_parent_role_names[0] }}"
origin_role_files: "{{ ansible_parent_role_paths[0] }}/files"

base_package: "{{ origin_role_name }}"
additional_packages: []
pkgbuild_urls: []

new_directories: []

configuration_source: "{{ origin_role_files }}/configuration"
configuration_destination: "{{ xdg_config_home }}/{{ origin_role_name }}"
configuration_mode: 0700
link_configuration_children: false
link_configuration_as_root: no
force_to_overwrite_configuration: false

systemd_units_user: []
systemd_units_system: []
systemd_units_custom_scope: user
systemd_units_custom_enabled: yes

provide_test_data: []
