- import_role:
    name: base_role
  vars:
    base_package: openssh
    new_directories: ["{{ xdg_cache_home }}/ssh"]
    configuration_destination: "{{ lookup('env', 'HOME') }}/.ssh"
    link_configuration_children: true
# TODO: use profile script for the caching
