- include_role:
    name: _install_packages

- include_role:
    name: _create_directories

# Link single file to ignore private keys etc.
- name: Link configuration file
  file:
    src: "{{ role_path }}/files/config"
    dest: "{{ config_directory }}/config"
    state: link
    force: yes

# TODO: intergrate as profile
- name: Link script for password caching
  file:
    src: "{{ role_path }}/files/enable_cache.sh"
    dest: "{{ config_directory }}/enable_cache.sh"
    state: link
    force: yes
