- import_role:
    name: base_role
  vars:
    base_package: openssh
    new_directories: ["{{ xdg_cache_home }}/ssh"]
    configuration_destination: "{{ lookup('env', 'HOME') }}/.ssh"
    link_configuration_children: true
    additional_packages:
      - x11-ssh-askpass # Password input when not in terminal
