- import_role:
    name: base_role
  vars:
    new_directories: ["{{ xdg_data_home }}/zsh"]

- name: Adjust globally where to search for user configuration
  copy:
    src: "{{ role_path }}/files/zshenv"
    dest: /etc/zsh/zshenv
    mode: 0644
  become: yes

- name: Change users default shell
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/bin/zsh
  become: yes
