#! /usr/bin/bash

# Fix sizing of broken visual component if resolution has changed.
systemctl --user restart wallpaper.service || true
systemctl --user restart polybar.service || true

notify-send -i display "Display profile" "Changed to: '$AUTORANDR_CURRENT_PROFILE'"

# vim: filetype=sh
