- import_role:
    name: base_role
  vars:
    base_package: networkmanager
    additional_packages:
      - macchanger # Change MAC address via custom dispatcher
    configuration_destination: "/etc/NetworkManager"
    link_configuration_children: true
    link_configuration_as_root: yes
    force_to_overwrite_configuration: true
    configuration_mode: 0744
    systemd_units:
      - NetworkManager.service
      - NetworkManager-dispatcher.service
    systemd_scope: system
