- include_role:
    name: _install_packages

- name: Copy dispatcher hooks
  copy:
    src: "{{ role_path }}/files/dispatcher.d/"
    dest: "{{ dispatcher_directory }}"
    mode: 0755
  become: yes

- include_role:
    name: _enable_start_services
