variables:
  git_available: >-
    command -v git > /dev/null ||
    (
    echo "Install git...";
    sudo pacman -Sy --noconfirm --needed git &&
    echo "Git installed."
    )

  git_clone: >-
    ( {{@@ git_available @@}} ) &&
    git clone --depth 1

  trizen_install: >-
    echo "Install trizen...";
    rm -rf /tmp/trizen;
    git clone https://aur.archlinux.org/trizen.git /tmp/trizen &&
    cd /tmp/trizen &&
    makepkg --syncdeps --install --noconfirm &&
    echo "Trizen installed."

  trizen_available: >-
    command -v trizen > /dev/null ||
    (
    ( {{@@ git_available @@}} ) &&
    ( {{@@ trizen_install @@}} )
    )

  install_package: >-
    ( {{@@ trizen_available @@}} ) &&
    trizen -S --needed --noconfirm

  yarn_available: >-
    command -v yarn > /dev/null ||
    ( {{@@ install_package @@}} yarn)

  yarn_install: >-
    ( {{@@ yarn_available @@}} ) &&
    yarn global add --non-interactive

  rustup_available: >-
    command -v rustup > /dev/null ||
    (
    {{@@ install_package @@}} rustup &&
    rustup toolchain install nightly &&
    rustup default nightly
    )

  rustup_install: >-
    ( {{@@ rustup_available @@}} ) &&
    rustup component add

  cargo_install: >-
    ( {{@@ rustup_available @@}} ) &&
    cargo install

  pip2_available: >-
    command -v pip2 > /dev/null ||
    ( {{@@ install_package @@}} python2-pip)

  install_pip2: >-
    ( {{@@ pip2_available @@}} ) &&
    pip2 install --user

  pip3_available: >-
    command -v pip3 > /dev/null ||
    ( {{@@ install_package @@}} python-pip)

  install_pip3: >-
    ( {{@@ pip3_available @@}} ) &&
    pip3 install --user

# vim: nospell
