config:
  dotpath: ../dotfiles
  showdiff: true
  keepdot: true # required by Zsh for example
  link_on_import: link
  link_dotfile_default: link
  import_variables:
    - variables.d/common.yaml
    - variables.d/installation.yaml
    - variables.d/unique.yaml
    - variables.d/fake.yaml

  import_actions:
    - actions.d/common.yaml
    - actions.d/installation.yaml
    - actions.d/unique.yaml
    - actions.d/fake.yaml

  import_configs:
    - configs.d/organization.yaml
    - configs.d/data.yaml
    - configs.d/multimedia.yaml

? dotfiles

profiles:
  kautz:
    include:
      - organization
      - data
      - multimedia

# vim: nospell
