extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:promise/recommended
  - plugin:react/recommended
  - plugin:prettier/recommended

plugins:
  - import,
  - promise,
  - react,
  - prettier

env:
  browser: true,
  node: true,
  mocha: true,
  es6: true

rules:
  'prettier/prettier': error
