- import_role:
    name: base_role
  vars:
    base_package: xorg # actually a big group of packages
    additional_packages:
      - xorg-xinit # Start xorg server, window manger etc.
      - xsel # Work with mouse selection

- name: Set keyboard mapping to support international characters with `altgr`
  shell: localectl --no-convert set-x11-keymap us pc104 altgr-intl
  become: yes

# Manually link this service unit and **NOT** enable it.
# Other services that should run after the server has started can use this as
# reference. The initialization script of the server will start this unit to
# trigger all depending services.
# This is a work around until I manage to run the server as service itself
# behind a socket.
- name: Link systemd unit as artificial synchronization point
  shell: systemctl --user link "{{ role_path }}/files/xorg-server.service"
