- import_role:
    name: base_role
  vars:
    additional_packages:
      - mopidy-local # Plugin to play local audio files
      - mopidy-mpd # Pluin to support MPD interface
      - alsa-lib # Fix audio output
      - mpc # Remote control via Music Player Daemon interface
    new_directories:
      - "{{ xdg_cache_home }}/mopidy"
      - "{{ xdg_data_home }}/mopidy"
    provide_test_data:
      - audio

- name: "{{ origin_role_name }} - hint message"
  debug:
    msg: Run `mopidy local scan` to import local music.
