[colors.normal]
black = "#000000"
blue = "#0000ff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.selection]
background = "#76cce0"
text = "#131416"

[font]
size = 10

[font.normal]
family = "Source Code Pro"
style = "Regular"

[scrolling]
history = 0

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.7

[window.class]
instance = "Alacritty"
