env:
  # Fix variating font size issues on different displays
  WINIT_X11_SCALE_FACTOR: "1"

window:
  class:
    instance: Alacritty

scrolling:
  history: 0 # Use TMux instead

font:
  size: 10

  # Style property adopts automatically for bold or italic text
  normal:
    family: Source Code Pro
    style: Regular

colors:
  primary:
    background: "#000000"
    foreground: "#5fd7ff"

  # The default colors are too opinionated and not clean.
  normal:
    black: "#000000"
    white: "#ffffff"
    red: "#ff0000"
    green: "#00ff00"
    blue: "#0000ff"
    yellow: "#ffff00"
    magenta: "#ff00ff"
    cyan: "#00ffff"

  selection:
    text: "#282a2e"
    background: "#d7ff5f"

background_opacity: 0.7

selection:
  save_to_clipboard: true
