- import_role:
    name: base_role
  vars:
    base_package: ""
    additional_packages:
      - thinkfan
      - lm_sensors
      - sof-firmware # Make sound working on new models
      - tlp # Improve battery
      - acpi_call # Kernel module for tlp
    systemd_units_system:
      - thinkfan.service
      - lm_sensors.service
      - tlp.service

- name: Enable ThinkPad ACPI
  shell: |
    echo "options thinkpad_acpi fan_control=1" | sudo tee /etc/modprobe.d/thinkfan.conf
    modprobe -rv thinkpad_acpi
    modprobe -v thinkpad_acpi
  become: yes

- name: Detect sensors
  shell: sensors-detect --auto
  become: yes

- name: Copy Thinkfan configuration
  file:
    src: "{{ role_path }}/files/thinkfan.conf"
    dest: /etc/thinkfan.conf
    mode: 0644
    force: yes
  become: true
