config:
  dotpath: ../../dotfiles
  link_dotfile_default: link

dotfiles:
  mutt:
    actions:
      - install_by_package_manager neomutt
      - install_by_package_manager ripmime
      - install_by_package_manager lynx
      - make_directory '{{@@ env["MAIL_DIR"] @@}}'
      - make_directory '{{@@ env["MUTT_CACHE"] @@}}'
      - change_mode u+rwx,g=,o= '{{@@ env["XDG_CONFIG_HOME"] @@}}/mutt/accounts'
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/mutt'
    src: mutt

  isync:
    actions:
      - install_by_package_manager isync
      - install_by_package_manager gnupg
      - make_directory '{{@@ env["MAIL_DIR"] @@}}'
      - make_directory '{{@@ env["ISYNC_CACHE_DIR"] @@}}'
      - make_directory '{{@@ env["ISYNC_STORE_DIR_LIST"] @@}}'
      - isync_sync
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/isync'
    src: isync

  notmuch:
    actions:
      - install_by_package_manager notmuch
      - make_directory '{{@@ env["MAIL_DIR"] @@}}'
      - notmuch_index
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/notmuch'
    src: notmuch

  notmuch_hooks:
    actions:
      - change_mode +X '{{@@ env["NOTMUCH_HOOKS_DIR"] @@}}/*'
    dst: '{{@@ env["NOTMUCH_HOOKS_DIR"] @@}}'
    src: notmuch/hooks

  msmtp:
    actions:
      - install_by_package_manager msmtp
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/msmtp'
    src: msmtp

  urlscan:
    actions:
      - install_by_package_manager urlscan-git
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/urlscan'
    src: urlscan

  mailcap:
    dst: '{{@@ env["HOME"] @@}}/.mailcap'
    src: mailcap

  vdirsyncer:
    actions:
      - install_by_package_manager vdirsyncer
      - install_by_package_manager python-requests-oauthlib
      - install_by_package_manager gnupg
      - make_directory '{{@@ env["CONTACT_DIR"] @@}}'
      - make_directory '{{@@ env["CALENDAR_DIR"] @@}}'
      - make_directory '{{@@ env["VDIRSYNCER_CACHE_DIR"] @@}}'
      - vdirsyncer_sync
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/vdirsyncer'
    src: vdirsyncer

  khal:
    actions:
      - install_by_package_manager khal
      - make_directory '{{@@ env["CALENDAR_DIR"] @@}}'
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/khal'
    src: khal

  khard:
    actions:
      - install_by_package_manager khard
      - make_directory '{{@@ env["CONTACT_DIR"] @@}}'
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/khard'
    src: khard

  orgatimer:
    actions:
      - install_by_script https://raw.githubusercontent.com/weilbith/orgatimer/master/install.sh install
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/orgatimer'
    src: orgatimer

profiles:
  organization:
    dotfiles:
      - mutt
      - isync
      - notmuch
      - notmuch_hooks
      - msmtp
      - urlscan
      - mailcap
      - vdirsyncer
      - khal
      - khard
      - orgatimer

# vim: nospell
