config:
  dotpath: ../../dotfiles
  link_dotfile_default: link
  keepdot: true

dotfiles:
  neovim:
    actions:
      - install_by_package_manager neovim-git
      - install_by_package_manager python-pynvim
      - install_by_package_manager neovim-remote
      - install_by_package_manager yad
      - make_directory '{{@@ env["XDG_DATA_HOME"] @@}}/nvim/session'
      - make_directory '{{@@ env["XDG_DATA_HOME"] @@}}/nvim/spell'
      - make_directory '{{@@ env["XDG_DATA_HOME"] @@}}/nvim/tags'
      - make_directory '{{@@ env["XDG_DATA_HOME"] @@}}/nvim/files/backup'
      - make_directory '{{@@ env["XDG_DATA_HOME"] @@}}/nvim/files/undo'
      - make_directory '{{@@ env["XDG_DATA_HOME"] @@}}/nvim/files/info'
      # TODO dein plugin manager
      - message 'Start NeoVim once to trigger installation of plugins automatically in asynchronous mode.'
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/nvim'
    src: nvim

  latex:
    actions:
      - install_by_package_manager texlive-most
      - remove_fake_file
      # Linting is separated
    dst: /tmp/fake
    src: fake

  ctags:
    actions:
      - install_by_package_manager universal-ctags-git
      - clone_tool https://github.com/jszakmeister/markdown2ctags.git markdown2ctags
    dst: '{{@@ env["HOME"] @@}}/.ctags.d'
    src: ctags

  editor_config:
    actions:
      - install_by_package_manager editorconfig-core-c
      - remove_fake_file
    dst: /tmp/fake
    src: fake

  languagetool:
    actions:
      - install_by_package_manager languagetool
    dst: '{{@@ env["XDG_CONFIG_HOME"]}}/'
    src: languagetool.cfg

  linting:
    actions:
      - install_by_package_manager shellcheck # Shell
      - install_by_package_manager uncrustify # C/Java-related
      - install_by_package_manager nodejs-jsonlint # JSON
      - install_by_package_manager eslint # Javascript
      - install_by_pip 3 vim-vint # Vim
      - download_binary https://github.com/vmchale/tomlcheck/releases/download/0.1.0.38/tomlcheck-x86_64-unkown-linux-gnu tomlcheck # TOML
      - install_by_package_manager solium # Solidity
      - install_by_yarn solhint # Solidity
      - install_by_pip 3 flake8 # Python
      - install_by_pip 3 mypy # Python
      - install_by_cargo racer # Rust
      - install_by_package_manager proselint # Actual Text
      - install_by_package_manager ansible-lint
      - install_by_package_manager tflint
      - install_by_package_manager luacheck
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/'
    link: link_children
    src: linting

  formatting:
    actions:
      - install_by_package_manager shfmt # Shell
      - install_by_package_manager prettier # Omni-web-related
      - install_by_package_manager fixjson # JSON
      - install_by_pip 3 black # Python
      - install_by_package_manager python-isort # Python
      - install_by_pip 3 docformatter # Python
      - install_by_rustup rustfmt # Rust
      - install_by_rustup nodejs-lua-fmt # Lua
      - remove_fake_file
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/'
    link: link_children
    src: formatting

  completion:
    actions:
      - install_by_package_manager tern # JavaScript
      - remove_fake_file
    dst: /tmp/fake
    src: fake

  language_servers:
    actions:
      - install_by_package_manager python-language-server
      - install_by_package_manager python-rope # TODO: install as dependecy for pyls
      - install_by_package_manager typescript-language-server-bin
      - install_by_package_manager bash-language-server
      - install_by_package_manager vscode-css-languageserver-bin
      - install_by_package_manager dockerfile-language-server-bin
      - install_by_package_manager vscode-html-languageserver-bin
      - install_by_package_manager vscode-json-languageserver-bin
      - install_by_package_manager rust-analyzer-bin
      - install_by_package_manager terraform-lsp-bin
      - install_by_package_manager texlab-git
      - install_by_package_manager vim-language-server
      - install_by_package_manager vue-language-server
      - install_by_package_manager yaml-language-server-bin
      # - install_by_package_manager lua-dkjson

profiles:
  writing:
    dotfiles:
      - neovim
      - latex
      - ctags
      - editor_config
      - linting
      - formatting
      - completion

# vim: nospell
