#!/bin/bash

systemctl --user import-environment DISPLAY XAUTHORITY DBUS_SESSION_BUS_ADDRESS
systemctl --user restart xautolock redshift picom unclutter greenclip xbindkeys

systemctl --user start xorg-server

exec i3

# vim: filetype=sh
