config:
  dotpath: ../../dotfiles
  link_dotfile_default: link

dotfiles:
  git:
    actions:
      - install_by_package_manager git
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/git'
    src: git

  hub:
    actions:
      - install_by_package_manager hub
      - message 'Make sure to provide an access token to {{@@ env["XDG_CONFIG_HOME"] @@}}/hub!'
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/hub'
    src: hub

  ranger:
    actions:
      - install_by_package_manager ranger
      - install_by_package_manager python-paramiko
      - install_by_package_manager python-pillow
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/ranger'
    src: ranger

  udisk:
    actions:
      - install_by_package_manager udisks2
      - install_by_package_manager ntfs-3g
      - link_permissioned udisk/99-udisk2.rules /etc/udev/rules.d/
      - link_permissioned udisk/media.conf /etc/tmpfiles.d/
      - enable_start_service udisks2.service
      - remove_fake_file
    # TODO: Fix this variable shit:
    # dst: '{{@@ fake_file_destination @@}}'
    dst: /tmp/fake
    # src: '{{@@ fake_file_source @@}}'
    src: fake

  bashmount:
    actions:
      - install_by_package_manager bashmount
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/bashmount'
    src: bashmount

  midnight_commander:
    actions:
      - install_by_package_manager mc
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/mc'
    src: mc

  midnight_commander_skins:
    dst: '{{@@ env["XDG_DATA_HOME"] @@}}/mc'
    src: mc/skins

  syncthing:
    actions:
      - install_by_package_manager syncthing
      - install_by_package_manager inotify-tools
      - enable_start_service_user syncthing.service
      - remove_fake_file
    dst: /tmp/fake
    src: fake

  restic:
    actions:
      - install_by_package_manager restic
      - remove_fake_file
    dst: /tmp/fake
    src: fake

profiles:
  data:
    dotfiles:
      - git
      - hub
      - ranger
      - udisk
      - bashmount
      - syncthing
      - restic
      # - midnight_commander # outdated in favor of ranger
      # - midnight_commander_skins # outdated in favor of ranger

# vim: nospell
