config:
  dotpath: ../../dotfiles
  link_dotfile_default: link

dotfiles:
  bashmount:
    actions:
      - install_by_package_manager bashmount
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/bashmount'
    src: bashmount

  midnight_commander:
    actions:
      - install_by_package_manager mc
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/mc'
    src: mc

  midnight_commander_skins:
    dst: '{{@@ env["XDG_DATA_HOME"] @@}}/mc'
    src: mc/skins

  syncthing:
    actions:
      - install_by_package_manager syncthing
      - install_by_package_manager inotify-tools
      - enable_start_service_user syncthing.service
      - remove_fake_file
    dst: /tmp/fake
    src: fake

  restic:
    actions:
      - install_by_package_manager restic
      - remove_fake_file
    dst: /tmp/fake
    src: fake

profiles:
  data:
    dotfiles:
      - git
      - hub
      - ranger
      - udisk
      - bashmount
      - syncthing
      - restic
      # - midnight_commander # outdated in favor of ranger
      # - midnight_commander_skins # outdated in favor of ranger

# vim: nospell
