config:
  dotpath: ../../dotfiles
  link_dotfile_default: link

dotfiles:
  htop:
    actions:
      - install_by_package_manager htop
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/htop'
    src: htop

  fwupd:
    actions:
      - install_by_package_manager fwupd
      - remove_fake_file
    dst: /tmp/fake
    src: fake

profiles:
  misc:
    dotfiles:
      - htop
      - fwupd

# vim: nospell
