dotfiles:
  ncmpcpp:
    actions:
      - install_by_package_manager ncmpcpp
      - make_directory '{{@@ env["NCMCPP_CACHE_DIR"] @@}}'
      - make_directory '{{@@ env["NCMCPP_LYRICS_DIR"] @@}}'
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/ncmpcpp'
    src: ncmpcpp

  beets:
    actions:
      - install_by_package_manager beets
      - install_by_package_manager --asdeps python-confuse # configuration stuff
      - install_by_package_manager --asdeps python-requests # fetchart plugin
      - install_by_package_manager --asdeps python-pylast # lastgenre plugin
      - install_by_package_manager --asdeps python-pyacoustid # chroma plugin
      - install_by_package_manager --asdeps imagemagic # art related plugins
      - make_directory '{{@@ env["BEETS_DATA_DIR"] @@}}'
      - make_directory '{{@@ env["BEETS_CACHE_DIR"] @@}}'
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/beets'
    src: beets

# vim: nospell
