config:
  dotpath: ../../dotfiles
  link_dotfile_default: link

dotfiles:
  # synaptics?
  #
  xautolock:
    actions:
      - install_by_package_manager xautolock
      - install_by_package_manager i3-lock-color
      - enable_start_service_user_custom xautostart.service
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/xautostart'
    src: xautostart

  autorandr:
    actions:
      - install_by_package_manager autorandr
        # Service!
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/autorandr'
    src: autorandr

  powerstatus10k:
    actions:
      - install_by_script https://raw.githubusercontent.com/weilbith/powerstatus10k/master/install.sh install
      - install_by_package_manager nerd-fonts-source-code-pro
      - install_by_package_manager inotify-tools
      - install_by_package_manager bluez-tools
      - install_by_package_manager python
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/powerstatus10k'
    src: powerstatus10k

  autostart:
    actions:
      - install_by_package_manager dex
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/autostart'
    src: autostart

  desktop_files:
    actions:
      - link_permissioned desktop-entries/* /usr/share/applications/
      - remove_fake_file
    dst: /tmp/fake
    src: fake

  greenclip:
    actions:
      - install_by_package_manager rofi-greenclip
      - make_directory '{{@@ env["XDG_CACHE_HOME"] @@}}/greenclip'
      - enable_start_service_user greenclip.service
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/greenclip.cfg'
    src: greenclip.cfg

  unclutter:
    actions:
      - install_by_package_manager unclutter
      - enable_start_service_user_custom unclutter.service
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/unclutter'
    src: unclutter

profiles:
  session:
    dotfiles:
      - x11_basics
      - i3wm
      - picom
      - pulse_audio
      - rofi
      - dunst
      - redshift
      - xautolock
      - ssh
      - autorandr
      - powerstatus10k
      - autostart
      - desktop_files
      - greenclip
      - unclutter

# vim: nospell
