dotfiles:
 autorandr:
    actions:
      - install_by_package_manager autorandr
        # Service!
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/autorandr'
    src: autorandr

  powerstatus10k:
    actions:
      - install_by_script https://raw.githubusercontent.com/weilbith/powerstatus10k/master/install.sh install
      - install_by_package_manager nerd-fonts-source-code-pro
      - install_by_package_manager inotify-tools
      - install_by_package_manager bluez-tools
      - install_by_package_manager python
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/powerstatus10k'
    src: powerstatus10k

# vim: nospell
