dotfiles:
  wget:
    actions:
      - install_by_package_manager wget
      - make_directory '{{@@ env["XDG_CACHE_HOME"] @@}}/wget'
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/wget'
    src: wget

  tool_collection:
    actions:
      - install_by_package_manager ripgrep-all-git # has config
      - install_by_package_manager exa # has environment
      - install_by_package_manager bat # has config
      - install_by_package_manager htop # has config

# vim: nospell
