actions:
  pre:
    install_by_package_manager: '{{@@ install_package @@}} {0}'
    install_by_yarn: '{{@@ yarn_install @@}} {0}'
    install_by_rustup: '{{@@ rustup_install @@}} {0}'
    install_by_cargo: '{{@@ cargo_install @@}} {0}'
    install_by_script: curl -s {0} | sudo bash -s - {1}
    clone_free: 'mkdir -p $(dirname {1}) && {{@@ git_clone @@}} {0} {1}'
    clone_tool: '{{@@ git_clone @@}} {0} {{@@ env["TOOLS_DIR"] @@}}/{1}'
    download_binary: 'sudo curl -L {0} -o /usr/bin/{1} && sudo chmod +x /usr/bin/{1}'
    install_by_pip: >-
      if [[ {0} -eq 2 ]]; then ({{@@ install_pip2 @@}} {1});
      else ({{@@ install_pip3 @@}} {1});
      fi

  post:
    # Mind that in the test Docker container no PID-1 systemd is available.
    enable_start_service: >-
      sudo systemctl 2&>1 /dev/null && 
      (
      sudo systemctl enable {0} &&
      sudo systemctl start {0}
      ) || echo

    enable_start_service_user: >-
      sudo systemctl 2&>1 /dev/null && 
      (
      sudo systemctl --user enable {0} &&
      sudo systemctl --user start {0}
      ) || echo

# vim: nospell
