actions:
  post:
    isync_sync: >-
      {{@@ mail_accounts_available @@}} &&
      (
      printf "\n{{@@ _dotfile_key @@}} - Attempt to synchronize mails. " &&
      ({{@@ yes_no_question @@}}) &&
      ({{@@ command_isync_sync @@}}) ||
      echo "You can synchronize manually with: {{@@ command_isync_sync @@}}"
      ) ||
      echo "Mail account files are not available needed to synchronize. Install 'mutt' target first."

    notmuch_index: >-
      printf "\n{{@@ _dotfile_key @@}} - Attempt to index local mail directory. " &&
      ({{@@ yes_no_question @@}}) &&
      ({{@@ command_notmuch_index @@}}) ||
      echo "You can index manually with: {{@@ command_notmuch_index @@}}"

    vdirsyncer_sync: >-
      printf "\n{{@@ _dotfile_key @@}} - Attempt to synchronize contacts and calendars. " &&
      ({{@@ yes_no_question @@}}) &&
      ({{@@ command_vdirsyncer_sync @@}}) ||
      echo "You can synchronize manually with: {{@@ command_vdirsyncer_sync @@}}"

    mopidy_scan_local: >-
      printf "\n{{@@ _dotfile_key @@}} - Attempt to scan local audio files for database. " &&
      ({{@@ yes_no_question @@}}) &&
      (
      ([[ -z "$(ps a | grep /usr/bin/mopidy | grep -v grep)" ]] && mopidy & );
      {{@@ command_mopidy_scan_local @@}};
      pkill mopidy
      ) ||
      echo "You can scan manually with: {{@@ command_mopidy_scan_local @@}}"

    zsh_set_configuration_directory: >-
      echo 'ZDOTDIR={{@@ env["XDG_CONFIG_HOME"] @@}}/zsh' | sudo tee -a /etc/zsh/zshenv

    zsh_set_as_default_shell: >-
      printf "\n{{@@ _dotfile_key @@}} - Attempt to set 'zsh' as default shell. " &&
      ({{@@ yes_no_question @@}}) &&
      ({{@@ command_zsh_set_as_default_shell @@}}) ||
      echo "You can set it manually with: {{@@ command_zsh_set_as_default_shell @@}}"

    # cerebro_place_appimage: >-
    #   mkdir -p {{@@ cerebro_appimage_location @@}} &&
    #   find {{@@ _dotdrop_dotpath @@}}/cerebro -type f -name '*.AppImage' \
    #   -exec ln -sf {} {{@@ cerebro_appimage_location @@}}/
    #
    # cerebro_start_temporally: >-
    #   TODO: start, sleep short, stop, install npm packages

# vim: nospell
