actions:
  post:
    isync_sync: >-
      {{@@ mail_accounts_available @@}} &&
      (
      printf "\n{{@@ _dotfile_key @@}} - Attempt to synchronize mails. " &&
      ({{@@ yes_no_question @@}}) &&
      {{@@ command_isync_sync @@}} ||
      echo "You can synchronize manually with: {{@@ command_isync_sync @@}}"
      ) ||
      echo "Mail account files are not available needed to synchronize. Install 'mutt' target first."

    notmuch_index: >-
      printf "\n{{@@ _dotfile_key @@}} - Attempt to index local mail directory. " &&
      ({{@@ yes_no_question @@}}) &&
      {{@@ command_notmuch_index @@}} ||
      echo "You can index manually with: {{@@ command_notmuch_index @@}}"

    vdirsyncer_sync: >-
      printf "\n{{@@ _dotfile_key @@}} - Attempt to synchronize contacts and calendars. " &&
      ({{@@ yes_no_question @@}}) &&
      {{@@ command_vdirsyncer_sync @@}} ||
      echo "You can synchronize manually with: {{@@ command_vdirsyncer_sync @@}}"

# vim: nospell
