- name: Setup focused on multimedia related stuff
  hosts: all
  roles:
    # images/photos
    - gimp
    - rawtherapee
    - digikam
    # audio/music
    - mopidy
    - ncmpcpp
    # videos
    - mpv
    # documents
    - zathura
