- name: Install base package
  aur: name=syncthing
  become: yes

- name: Install optional dependency packages
  aur:
    name:
      - inotify-tools # Observe filesystem events for auto-sync
  become: yes

# Syncthing mixes the keys and certificates into the configuration directory.
# Therefore I can't put all of them into the dotfiles and need to split it.
- name: Link single configuration file
  file:
    src: "{{ role_path }}/files/config.xml"
    dest: "{{ configuration_directory }}/config.xml"
    state: link
    force: yes

- name: Enable and start SystemD service
  systemd:
    name: syncthing.service
    enabled: yes
    state: started
    scope: user
