- include_role:
    name: _install_packages

# Syncthing mixes the keys and certificates into the configuration directory.
# Therefore I can't put all of them into the dotfiles and need to split it.
- name: Link single configuration file
  file:
    src: "{{ role_path }}/files/config.xml"
    dest: "{{ configuration_directory }}/config.xml"
    state: link
    force: yes

- include_role:
    name: _enable_start_services
