- import_role:
    name: base_role
  vars:
    additional_packages:
      - inotify-tools # Observe filesystem events for auto-sync
    link_configuration_children: true
    systemd_units: [syncthing.service]
