/home/thore/.config/zsh/alias.zsh:9: condition expected: $ext
#!/bin/bash

# Specify X11 configuration files.
XRESOURCES=$XDG_CONFIG_HOME/X11/xresources
XMODMAP=$XDG_CONFIG_HOME/X11/xmodmap
XBINDKEYS=$XDG_CONFIG_HOME/X11/xbindkeysrc

# Merge/load X11 configurations if they exist.
[[ -f "$XRESOURCES" ]] && xrdb -merge "$XRESOURCES"
[[ -f "$XMODMAP" ]] && xmodmap "$XMODMAP"
[[ -f "$XBINDKEYS" ]] && xbindkeys --file "$XBINDKEYS"

# Daemons
unclutter &
redshift &
pulseaudio --start -D &

# Autostart
dex -a &

# Window Manager
exec i3
