#!/bin/bash

# Specify X11 configuration files.
XRESOURCES=$XDG_CONFIG_HOME/X11/xresources
XMODMAP=$XDG_CONFIG_HOME/X11/xmodmap
XBINDKEYS=$XDG_CONFIG_HOME/X11/xbindkeysrc

# Merge/load X11 configurations if they exist.
[[ -f "$XRESOURCES" ]] && xrdb -merge "$XRESOURCES"
[[ -f "$XMODMAP" ]] && xmodmap "$XMODMAP"
[[ -f "$XBINDKEYS" ]] && xbindkeys --file "$XBINDKEYS"

# TODO: Fix that by the systemd script
systemctl --user import-environment DISPLAY XAUTHORITY

# Adopt the monitor setup (do that before the window manager starts)
command -v autorandr >/dev/null && autorandr --change

# Autostart
command -v dex >/dev/null && dex -a &

# Window Manager
exec i3

# vim: filetype=sh
