- name: "{{ origin_role_name }} - enable (custom) systemd unit(s)"
  systemd:
    name: "{{ item }}"
    scope: "{{ systemd_scope }}"
    enabled: yes
  become: "{{ systemd_scope == 'system' }}"
  with_items:
    - "{{ systemd_units }}"
    - "{{ lookup('files_in_role_directory', 'systemd', wantlist=True) }}"
