- name: "{{ origin_role_name }} - enable (custom) systemd unit(s)"
  when: lookup('env', 'USER') != 'circleci'
  systemd:
    name: "{{ item }}"
    scope: "{{ systemd_scope }}"
    enabled: yes
  become: "{{ systemd_scope == 'system' }}"
  with_items:
    - "{{ systemd_units }}"
    - "{{ lookup('role_directory_entries', 'systemd', wantlist=True) }}"

# Limit this to the user space so far.
- name: "{{ origin_role_name }} - make sure timer related services are only linked"
  when:
    - lookup('role_directory_entries', 'systemd') | length > 0
    - lookup('env', 'USER') != 'circleci'
  shell: |
    timer_services=$(systemctl --user list-timers --all --plain --no-legend --full | awk 'NF>1{print $NF}')
    for service in $timer_services; do
      unit_enabled=$(systemctl --user list-units $service --plain --no-legend)
      if [[ -n "$unit_enabled" ]]; then
        unit_path=$(systemctl --user show --property FragmentPath $service | cut -d "=" -f2)
        systemctl --user disable $service
        systemctl --user link $unit_path
      fi
    done
