- name: "{{ origin_role_name }} - install package(s) from registry"
  aur:
    name: "{{ item }}"
  with_items:
    - "{{ base_package }}"
    - "{{ additional_packages }}"

- name: "{{ origin_role_name }} - install package(s) by PKGBUILD files"
  shell: >
    cd $(mktemp -d);
    curl -O "{{ item }}";
    makepkg --syncdeps --install --needed --noconfirm
  with_items:
    - "{{ pkgbuild_urls }}"
