- name: "{{ origin_role_name }} - Block: link shared directory children for '{{ directory | basename }}'"
  when: lookup('role_directory_entries', directory | basename) | length > 0
  block:
    - name: "{{ origin_role_name }} - create {{ directory | basename }} directory"
      file:
        path: "{{ directory }}"
        state: directory

    - name: "{{ origin_role_name }} - link {{ directory | basename }} files"
      file:
        src: "{{ item }}"
        dest: "{{ directory }}/{{ item | basename }}"
        state: link
        mode: 0700
      with_items:
        - "{{ lookup('role_directory_entries', directory | basename, wantlist=True) }}"
