- name: "{{ origin_role_name }} - Block: link profile"
  when: lookup('role_directory_entries', 'profile') | length > 0
  block:
    - name: "{{ origin_role_name }} - create profile directory"
      file:
        path: "{{ profile_directory }}"
        state: directory

    - name: "{{ origin_role_name }} - link profile files"
      file:
        src: "{{ item }}"
        dest: "{{ profile_directory }}/{{ item | basename }}"
        state: link
        mode: 0700
      with_items:
        - "{{ lookup('role_directory_entries', 'profile', wantlist=True) }}"
