- stat:
    path: "{{ configuration_source }}"
  register: configuration_source_directory

- import_tasks: install_packages.yaml
- import_tasks: make_directories.yaml
- import_tasks: link_configuration.yaml
- import_tasks: link_environment.yaml
- import_tasks: link_profile.yaml
- import_tasks: enable_systemd_units.yaml
