- import_tasks: install_packages.yaml
- import_tasks: make_directories.yaml
- import_tasks: link_configuration.yaml
- import_tasks: enable_systemd_units.yaml

- name: "{{ origin_role_name }} - Block: link shared directories"
  include_tasks: link_shared_directory.yaml
  loop:
    - "{{ environment_directory }}"
    - "{{ profile_directory }}"
    - "{{ plugin_directory }}"
    - "{{ applications_directory }}"
  loop_control:
    loop_var: directory
